baseURL = "https://meisenlab.github.io/coding_site/"
languageCode = "en-us"
title = "Eisen Lab Coding Club"
theme = "noteworthy"
tags = ["brainstorming", "about"] 
publishDir = "docs"

summaryLength = 7 # Configure how long the post summary should be on the homepage.

[params]
	math = true
	# Blog description at the top of the homepage
	description = "Sharing coding knowledge for quarantine times"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	

	# Programming
    github = "https://github.com/meisenlab"


# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2


## Pigments
PygmentsCodeFences = true
PygmentsStyle = "monokai"

